apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-assinatura
  labels:
    app: app-assinatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-assinatura
  template:
    metadata:
      labels:
        app: app-assinatura
        monitoramento-prometheus: "enabled"
    spec:
      containers:
        - name: app-assinatura-container
          image: agptidocker/app-assinatura:3.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - -nginx.scrape-uri=http://localhost:80/stub_status
          ports:
            - containerPort: 9113
              name: metrics
---
# --- 3. Ingress ---
# O Ingress gere o acesso externo à sua aplicação.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-assinatura-ingress
  labels:
    app: app-assinatura
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "assinatura.k8s.local" # O domínio para aceder à aplicação
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-assinatura-service # Aponta para o Service correto
                port:
                  number: 80


